contractId: "product-post"
url: "http://localhost:3000/product"
method: "POST"
status: 201
payload: "
{
    \"productName\" : \"novo produto\",
    \"price\" : 1111.9
}
"
request: "
{
  \"$id\": \"product-request\",
  \"title\": \"Product Request\",
  \"description\": \"A product from Acme's catalog\",
  \"type\": \"object\",
  \"properties\": {
      \"productName\": {
        \"description\": \"Name of the product\",
        \"type\": \"string\"
      },
      \"price\": {
        \"description\": \"The price of the product\",
        \"type\": \"number\",
        \"exclusiveMinimum\": 0
      }
  },
  \"required\": [ \"productName\", \"price\" ]
}"

response: "
{
  \"$id\": \"product-response\",
  \"title\": \"Product Response\",
  \"description\": \"A product from Acme's catalog\",
  \"type\": \"object\",
  \"properties\": {
      \"id\": {
        \"description\": \"The unique identifier for a product\",
        \"type\": \"integer\"
      },
      \"productName\": {
        \"description\": \"Name of the product\",
        \"type\": \"string\"
      },
      \"price\": {
        \"description\": \"The price of the product\",
        \"type\": \"number\",
        \"exclusiveMinimum\": 0
      }
  },
  \"required\": [ \"id\", \"productName\", \"price\" ]
}"
